### ISSUE TITLE
Android Production Build Issue

### ISSUE THREAD

**Issue by onosol** [reggie3/react-native-webview-quilljs#21]
First off, this component is awesome! As far as iOS goes, everything works as expected. But on Android, everything works fine when I run the app on a debug build. BUT, we I run the app on Android device with a production build, no content is displayed in the Viewer and the Editor? Any idea what I might be missing that would cause it to fails to render content on an Android Production Build versus working just fine with a debug build?

**Comment by reggie3** [comment]
Thanks, and thanks for the report!  I'm seeing the same thing that you're seeing.  I'll see what I can do.  I'm kind of at a lost since it works in dev mode on both platforms, but in prod on only iOS.

Some notes for reference:
[react native webview android commit history](https://github.com/facebook/react-native/commits/84c965f0851dd4ca832c18a463e4577764c54244/Libraries/Components/WebView/WebView.android.js)

[react native webview iOS commit history](https://github.com/facebook/react-native/commit/634e7e11e3ad39e0b13bf20cc7722c0cfd3c3e28#diff-eb29dcb037331f7852621383e484d706)

**Comment by reggie3** [comment]
@onosol, I reverted back to a previous version of React Native, and published a version that should at least have the editor working, and may have the viewer working in Android.  It is available viat the issue-21 tag on npm, and can be installed like so:

npm install react-native-webview-quilljs@issue-21

Please give it a try and let me know if it's working for you.

**Comment by onosol** [comment]
@reggie3  - I am traveling for the next couple of weeks, so it will be a little while before I can test. Just curious, what version of react-native did you downgrade to?

**Comment by reggie3** [comment]
To 16.3.0-alpha.1

**Comment by onosol** [comment]
@reggie3, npm install react-native-webview-quilljs@issue-21 did not work for me.
Kind of at a lost on this one. I'm assuming it has to be a react-native issue in the end.

**Comment by reggie3** [comment]
Thanks for posting your workaround.  I'll have to do more research.  The WebViews should be looking for the HTML in the node packages assets/dist folder, so the requirement to copy the HTML files to `uri: 'file:///android_asset/reactQuillViewer-index.html'` is interesting.  I will have to see if it persists.
